# serverless.yml
service: nesinio-invoice-app
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: NesinTechnologies
custom:
  serverless-offline:
    port: 7777
plugins:
  - serverless-dotenv-plugin
  - serverless-offline  # serverless-offline needs to be last in the list
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true