# serverless.yml
service: nesinio-invoice-app

plugins:
  - serverless-offline # Place it at the top of plugin list
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: NesinTechnologies
functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"